baseURL = "https://docs.liagame.com/"
languageCode = "en-us"
title = "Lia Docs"
metadataformat = "yaml"
canonifyurls = true
enableEmoji = true
theme = "hugo-material-docs"

[params]
	# General information
	author = "lia"
	description = "Fighting for nerds."
	copyright = "Lia"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/liagame/lia-docs"

	logo = "static/images/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting themes
	highlight_css  = ""

	[params.palette]
	    # names can be found here: https://www.materialui.co/colors
    	primary = "green"
    	accent  = "light-green"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"

[social]
#	twitter = "liagame"
	github  = "liagame"
	email   = "hello@liagame.com"

[[menu.main]]
	name   = "Docs"
	url    = "/"
	weight = 2

[[menu.main]]
	parent = "Docs"
	name   = "Lia"
	url    = "/"
	weight = 1
	pre = "<img src='/static/images/home.svg' alt='home' style='width:1.1em;vertical-align: middle;'>"

[[menu.main]]
	parent = "Docs"
	name   = "Game description"
	url    = "game-description/"
	weight = 2

[[menu.main]]
	parent = "Docs"
	name   = "Game rules"
	url    = "game-rules/"
	weight = 3

[[menu.main]]
	parent = "Docs"
	name   = "Getting started"
	url    = "getting-started/"
	weight = 4

[[menu.main]]
	parent = "Docs"
	name   = "Lia CLI"
	url    = "lia-cli/"
	weight = 7

[[menu.main]]
	parent = "Docs"
	name   = "API"
	url    = "api/"
	weight = 8

[[menu.main]]
	parent = "Docs"
	name   = "Privacy policy"
	url    = "privacy-policy/"
	weight = 9


[[menu.examples]]
	parent = "Examples"
	name   = "Rotation"
	url    = "examples/rotation/"
	weight = 13

[[menu.examples]]
	parent = "Examples"
	name   = "Movement"
	url    = "examples/rotation/"
	weight = 13

[[menu.examples]]
	parent = "Examples"
	name   = "Shooting & ammo"
	url    = "examples/rotation/"
	weight = 13

[[menu.examples]]
	parent = "Examples"
	name   = "Follow points"
	url    = "examples/rotation/"
	weight = 13

[[menu.examples]]
	parent = "Examples"
	name   = "Pathfinding"
	url    = "examples/rotation/"
	weight = 13

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
