baseURL = "https://docs.liagame.com/"
languageCode = "en-us"
title = "Lia Docs"
metadataformat = "yaml"
canonifyurls = true
enableEmoji = true
theme = "hugo-material-docs"

[params]
	# General information
	author = "lia"
	description = "Fighting for nerds."
	copyright = "Lia"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/liagame/lia-docs"

	logo = "static/images/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting themes
	highlight_css  = ""

	[params.palette]
	    # names can be found here: https://www.materialui.co/colors
    	primary = "green"
    	accent  = "light-green"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"

[social]
#	twitter = "liagame"
	github  = "liagame"
	email   = "hello@liagame.com"

[[menu.main]]
	name   = "Docs"
	url    = "/"
	weight = 2

[[menu.main]]
	parent = "Docs"
	name   = "Lia"
	url    = "/"
	weight = 1
	pre = "<img src='/static/images/home.svg' alt='home' style='width:1.1em;vertical-align: middle;'>"

[[menu.main]]
	parent = "Docs"
	name   = "Game description"
	url    = "game-description/"
	weight = 2

[[menu.main]]
	parent = "Docs"
	name   = "Game rules"
	url    = "game-rules/"
	weight = 3

[[menu.main]]
	parent = "Docs"
	name   = "Getting started"
	url    = "getting-started/"
	weight = 4

[[menu.main]]
	parent = "Docs"
	name   = "Lia CLI"
	url    = "lia-cli/"
	weight = 7

[[menu.main]]
	parent = "Docs"
	name   = "API"
	url    = "api/"
	weight = 8

[[menu.main]]
	parent = "Docs"
	name   = "Common problems"
	url    = "common-problems/"
	weight = 9

[[menu.main]]
	parent = "Docs"
	name   = "Privacy policy"
	url    = "privacy-policy/"
	weight = 10

[[menu.examples]]
	parent = "Examples"
	name   = "Overview"
	url    = "examples/overview/"
	weight = 1

[[menu.examples]]
	parent = "Examples"
	name   = "Rotation"
	url    = "examples/rotation/"
	weight = 2

[[menu.examples]]
	parent = "Examples"
	name   = "Movement"
	url    = "examples/movement/"
	weight = 3

[[menu.examples]]
	parent = "Examples"
	name   = "Shooting & ammo"
	url    = "examples/shooting-and-ammo/"
	weight = 4

[[menu.examples]]
	parent = "Examples"
	name   = "Identifying the enemy"
	url    = "examples/identifying-the-enemy/"
	weight = 5

[[menu.examples]]
	parent = "Examples"
	name   = "Following path"
	url    = "examples/following-path/"
	weight = 6

[[menu.examples]]
	parent = "Examples"
	name   = "Pathfinding"
	url    = "examples/pathfinding/"
	weight = 7

[[menu.examples]]
	parent = "Examples"
	name   = "Multiple units"
	url    = "examples/multiple-units/"
	weight = 8

[[menu.tutorials]]
	parent = "Tutorials"
	name   = "Beginner tutorial - Part 1"
	url    = "tutorials/beginner-tutorial-part-1/"
	weight = 1

[[menu.tutorials]]
	parent = "Tutorials"
	name   = "Debugging your code"
	url    = "tutorials/debugging-your-code/"
	weight = 2

[[menu.tutorials]]
	parent = "Tutorials"
	name   = "Using an IDE"
	url    = "tutorials/using-ide/"
	weight = 3

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
